#!/usr/bin/env node

var child_process = require("child_process");

child_process.exec(`npx tsc -p sim`, { stdio: "inherit" }, function (err, stdout, stderr) {
    if (err) {
        throw new Error(err);
    }
    if (stderr) {
        console.error(stderr);
    }
    if (stdout) {
        console.log(stdout);
    }
});
